sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.index.content.grid.data_table#suggested':
            adyen:
                template: '@SyliusAdyenPlugin/admin/payment_method/index/content/grid/data_table/suggested/adyen.html.twig'
